version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: telemetry_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-telemetry_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 